-- =============================================================================
-- MiDentista · Esquema de base de datos (Supabase / PostgreSQL)
--
-- Cómo usarlo: Supabase → SQL Editor → New query → pegar TODO este archivo → Run.
-- Se puede ejecutar varias veces: no borra datos existentes.
--
-- Además, en Supabase → Authentication → Sign In / Providers → Email:
--   · Desactivar "Allow new users to sign up" (nadie puede crearse una cuenta).
--   · Crear la cuenta de la clínica en Authentication → Users → Add user.
-- =============================================================================


-- 1. TABLA DE CITAS -----------------------------------------------------------

create table if not exists public.citas (
  id                bigint generated by default as identity primary key,
  creado_en         timestamptz not null default now(),
  servicio_id       text        not null default 'consulta-general',
  dentista_id       text,
  fecha_cita        date        not null,
  hora_cita         time        not null,
  paciente_nombre   text        not null,
  paciente_telefono text        not null,
  paciente_email    text,
  estado            text        not null default 'pendiente',
  notas             text
);

-- Columnas nuevas, por si la tabla venía de una versión anterior del proyecto.
alter table public.citas add column if not exists estado text not null default 'pendiente';
alter table public.citas add column if not exists notas text;

comment on table public.citas is 'Solicitudes de cita enviadas desde el sitio web';
comment on column public.citas.estado is 'pendiente | confirmada | atendida | cancelada';

-- Reglas de datos. "not valid" = se aplican a las filas nuevas sin revisar las antiguas.
alter table public.citas drop constraint if exists citas_estado_valido;
alter table public.citas add constraint citas_estado_valido
  check (estado in ('pendiente', 'confirmada', 'atendida', 'cancelada')) not valid;

alter table public.citas drop constraint if exists citas_datos_validos;
alter table public.citas add constraint citas_datos_validos check (
  char_length(paciente_nombre) between 3 and 100
  and paciente_telefono ~ '^\+?[0-9]{7,15}$'
  and (paciente_email is null or char_length(paciente_email) <= 120)
  and char_length(servicio_id) <= 60
  and (notas is null or char_length(notas) <= 500)
) not valid;

-- Un mismo horario no puede tener dos citas activas.
-- (Si falla al crearlo, ya existen citas duplicadas: cancela una de ellas.)
create unique index if not exists citas_horario_unico
  on public.citas (fecha_cita, hora_cita)
  where estado <> 'cancelada';

create index if not exists citas_fecha_idx on public.citas (fecha_cita);


-- 2. ADMINISTRADORES ----------------------------------------------------------
-- Tener una cuenta en Supabase Auth no basta para ver las citas:
-- el correo debe estar en esta tabla.

create table if not exists public.administradores (
  email     text primary key,
  creado_en timestamptz not null default now()
);

alter table public.administradores enable row level security;
-- Sin políticas: nadie puede leer ni modificar esta tabla desde la API.
-- Solo la usa la función es_admin() (security definer).

insert into public.administradores (email)
values ('midentista114@gmail.com')
on conflict (email) do nothing;

create or replace function public.es_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.administradores
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.es_admin() from public;
grant execute on function public.es_admin() to anon, authenticated;


-- 3. VALIDACIÓN AL CREAR UNA CITA (anti-spam y reglas del negocio) ------------

create or replace function public.validar_nueva_cita()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  hoy        date := (now() at time zone 'America/La_Paz')::date;
  pendientes integer;
begin
  if new.fecha_cita < hoy then
    raise exception 'La fecha de la cita no puede estar en el pasado.' using errcode = 'P0001';
  end if;

  if new.fecha_cita > hoy + 60 then
    raise exception 'Solo se pueden reservar citas con hasta 60 días de anticipación.' using errcode = 'P0001';
  end if;

  if extract(isodow from new.fecha_cita) = 7 then
    raise exception 'La clínica no atiende los domingos.' using errcode = 'P0001';
  end if;

  select count(*) into pendientes
  from public.citas
  where paciente_telefono = new.paciente_telefono
    and fecha_cita >= hoy
    and estado in ('pendiente', 'confirmada');

  if pendientes >= 3 then
    raise exception 'Este teléfono ya tiene 3 citas por atender. Comunícate con la clínica por WhatsApp.'
      using errcode = 'P0001';
  end if;

  -- Toda cita nueva entra como pendiente y con la hora real del servidor.
  new.estado    := 'pendiente';
  new.creado_en := now();
  return new;
end;
$$;

drop trigger if exists citas_validar_insert on public.citas;
create trigger citas_validar_insert
  before insert on public.citas
  for each row execute function public.validar_nueva_cita();


-- 4. HORARIOS OCUPADOS (sin exponer datos personales) --------------------------
-- El formulario público solo necesita saber qué horas están tomadas.

create or replace function public.horarios_ocupados(p_fecha date)
returns table (hora text)
language sql
stable
security definer
set search_path = public
as $$
  select left(hora_cita::text, 5)
  from public.citas
  where fecha_cita = p_fecha
    and estado <> 'cancelada'
  order by 1;
$$;

revoke all on function public.horarios_ocupados(date) from public;
grant execute on function public.horarios_ocupados(date) to anon, authenticated;


-- 5. SEGURIDAD A NIVEL DE FILAS (RLS) -----------------------------------------
-- Visitante anónimo: solo puede CREAR citas (no leerlas, ni editarlas, ni borrarlas).
-- Administrador: puede ver, actualizar y eliminar.

alter table public.citas enable row level security;

-- Permisos base de la API (RLS decide después qué filas se pueden tocar).
grant usage on schema public to anon, authenticated;
grant insert on public.citas to anon, authenticated;
grant select, update, delete on public.citas to authenticated;

-- Borra cualquier política anterior de la tabla para empezar limpio.
do $$
declare
  politica record;
begin
  for politica in
    select policyname from pg_policies where schemaname = 'public' and tablename = 'citas'
  loop
    execute format('drop policy %I on public.citas', politica.policyname);
  end loop;
end;
$$;

create policy "publico_crea_citas" on public.citas
  for insert to anon, authenticated
  with check (estado = 'pendiente');

create policy "admin_lee_citas" on public.citas
  for select to authenticated
  using (public.es_admin());

create policy "admin_actualiza_citas" on public.citas
  for update to authenticated
  using (public.es_admin())
  with check (public.es_admin());

create policy "admin_elimina_citas" on public.citas
  for delete to authenticated
  using (public.es_admin());
